### ISSUE TITLE
Nowe techniki wizualizacji - back-end

### ISSUE THREAD

**Issue by DocentSzachista** [Droniu/emotion-visualisation#8]
Dr Szyc podczas spotkania proponował następujące:
- TSNE (obarczone komentarzem, że może być trudne dodawanie nowych próbek) -> moim zdaniem wybrać może lepiej U-map [tutaj](https://pair-code.github.io/understanding-umap/) jest niby szybsze i lepsze xd Zrobiine #11 
- Spróbować znormalizować dane i je wyświetlić na wykresie PCA w 3D: Normalizacja L_2 / skalowanie danych -> PCA -> Normalizacja L_2 - Zrobione w #10 
- Możliwość klasteryzacji danych (za dużo się nie wypowiedział, trzeba by było doczytać) [wykorzystanie k-means i pca do wizualizacji klastórw](https://medium.com/analytics-vidhya/implementation-of-principal-component-analysis-pca-in-k-means-clustering-b4bc0aa79cb6)
- Możliwość wizualizacji otoczenia punktów (Do doczytania/dopytania) -> zrobić tylko wtedy jeżeli będziemy chcieli

**Comment by AgataRubaszewska** [comment]
Ja mogę zrobić klasteryzację
